import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

def getCost(val1,val2,val3,val4):
# 	Flame sensor- 0 or 1
# 	PIR sensor - 0 or 1
# 	Distance - 0 to 150cm
# 	Temperature - 0 to 50degree
	flame=ctrl.Antecedent(np.arange(0,1,0.1),'flame')
	pir=ctrl.Antecedent(np.arange(0,1,0.1),'pir')
	distance=ctrl.Antecedent(np.arange(0,150,1),'distance')
	temp=ctrl.Antecedent(np.arange(0,50,1),'temp')
	cost=ctrl.Consequent(np.arange(0,10,1),'cost')

	flame['low']=fuzz.trapmf(flame.universe,[-0.2,-0.1,0,0.5])
	flame['medium']=fuzz.trimf(flame.universe,[0,0.5,1])
	flame['high']=fuzz.trapmf(flame.universe,[0.5,1,1.1,1.2])

	pir['low']=fuzz.trapmf(pir.universe,[-2.2,-1.1,0,0.5])
	pir['medium']=fuzz.trimf(pir.universe,[0,0.5,1])
	pir['high']=fuzz.trapmf(pir.universe,[0.5,1,1.1,1.2])

	distance['low']=fuzz.trapmf(distance.universe,[-0.9,-0.8,0,75])
	distance['medium']=fuzz.trimf(distance.universe,[0,75,150])
	distance['high']=fuzz.trapmf(distance.universe,[75,150,150.1,150.2])

	temp['low']=fuzz.trapmf(temp.universe,[-2,-1,0,25])
	temp['medium']=fuzz.trimf(temp.universe,[0,25,50])
	temp['high']=fuzz.trapmf(temp.universe,[25,50,50.1,50.2])

	cost['verylow']=fuzz.trapmf(cost.universe,[-0.2,-0.1,0,3])
	cost['low']=fuzz.trimf(cost.universe,[0,3,6])
	cost['medium']=fuzz.trimf(cost.universe,[3,6,8])
	cost['high']=fuzz.trimf(cost.universe,[6,8,20])
	cost['veryhigh']=fuzz.trapmf(cost.universe,[8,10,10.1,10.2])

	rule1 = ctrl.Rule(flame['high'] & distance['high'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule2 = ctrl.Rule(flame['high'] & distance['high'] & pir['high'] & temp['medium'] , cost['medium'])
	rule3 = ctrl.Rule(flame['high'] & distance['high'] & pir['high'] & temp['low'] , cost['verylow'])
	rule4 = ctrl.Rule(flame['high'] & distance['high'] & pir['medium'] & temp['high'] , cost['high'])
	rule5 = ctrl.Rule(flame['high'] & distance['high'] & pir['medium'] & temp['medium'] , cost['medium'])
	rule6 = ctrl.Rule(flame['high'] & distance['high'] & pir['medium'] & temp['low'] , cost['low'])
	rule7 = ctrl.Rule(flame['high'] & distance['high'] & pir['low'] & temp['high'] , cost['high'])
	rule8 = ctrl.Rule(flame['high'] & distance['high'] & pir['low'] & temp['medium'] , cost['high'])
	rule9 = ctrl.Rule(flame['high'] & distance['high'] & pir['low'] & temp['low'] , cost['verylow'])
	rule10 = ctrl.Rule(flame['high'] & distance['medium'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule11 = ctrl.Rule(flame['high'] & distance['medium'] & pir['high'] & temp['medium'] , cost['high'])
	rule12 = ctrl.Rule(flame['high'] & distance['medium'] & pir['high'] & temp['low'] , cost['low'])
	rule13 = ctrl.Rule(flame['high'] & distance['medium'] & pir['medium'] & temp['high'] , cost['veryhigh'])
	rule14 = ctrl.Rule(flame['high'] & distance['medium'] & pir['medium'] & temp['medium'] , cost['high'])
	rule15 = ctrl.Rule(flame['high'] & distance['medium'] & pir['medium'] & temp['low'] , cost['medium'])
	rule16 = ctrl.Rule(flame['high'] & distance['medium'] & pir['low'] & temp['high'] , cost['high'])
	rule17 = ctrl.Rule(flame['high'] & distance['medium'] & pir['low'] & temp['medium'] , cost['medium'])
	rule18 = ctrl.Rule(flame['high'] & distance['medium'] & pir['low'] & temp['low'] , cost['low'])
	rule19 = ctrl.Rule(flame['high'] & distance['low'] & pir['high'] & temp['high'] , cost['high'])
	rule20 = ctrl.Rule(flame['high'] & distance['low'] & pir['high'] & temp['medium'] , cost['medium'])
	rule21 = ctrl.Rule(flame['high'] & distance['low'] & pir['high'] & temp['low'] , cost['low'])
	rule22 = ctrl.Rule(flame['high'] & distance['low'] & pir['medium'] & temp['high'] , cost['high'])
	rule23 = ctrl.Rule(flame['high'] & distance['low'] & pir['medium'] & temp['medium'] , cost['medium'])
	rule24 = ctrl.Rule(flame['high'] & distance['low'] & pir['medium'] & temp['low'] , cost['low'])
	rule25 = ctrl.Rule(flame['high'] & distance['low'] & pir['low'] & temp['high'] , cost['high'])
	rule26 = ctrl.Rule(flame['high'] & distance['low'] & pir['low'] & temp['medium'] , cost['medium'])
	rule27 = ctrl.Rule(flame['high'] & distance['low'] & pir['low'] & temp['low'] , cost['low'])
	rule28 = ctrl.Rule(flame['medium'] & distance['high'] & pir['high'] & temp['high'] , cost['high'])
	rule29 = ctrl.Rule(flame['medium'] & distance['high'] & pir['high'] & temp['medium'] , cost['high'])
	rule30 = ctrl.Rule(flame['medium'] & distance['high'] & pir['high'] & temp['low'] , cost['medium'])
	rule31 = ctrl.Rule(flame['medium'] & distance['high'] & pir['medium'] & temp['high'] , cost['high'])
	rule32 = ctrl.Rule(flame['medium'] & distance['high'] & pir['medium'] & temp['medium'] , cost['high'])
	rule33 = ctrl.Rule(flame['medium'] & distance['high'] & pir['medium'] & temp['low'] , cost['low'])
	rule34 = ctrl.Rule(flame['medium'] & distance['high'] & pir['low'] & temp['high'] , cost['high'])
	rule35 = ctrl.Rule(flame['medium'] & distance['high'] & pir['low'] & temp['medium'] , cost['medium'])
	rule36 = ctrl.Rule(flame['medium'] & distance['high'] & pir['low'] & temp['low'] , cost['low'])
	rule37 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule38 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['high'] & temp['medium'] , cost['medium'])
	rule39 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['high'] & temp['low'] , cost['low'])
	rule40 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['medium'] & temp['high'] , cost['high'])
	rule41 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['medium'] & temp['medium'] , cost['medium'])
	rule42 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['medium'] & temp['low'] , cost['low'])
	rule43 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['low'] & temp['high'] , cost['medium'])
	rule44 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['low'] & temp['medium'] , cost['medium'])
	rule45 = ctrl.Rule(flame['medium'] & distance['medium'] & pir['low'] & temp['low'] , cost['verylow'])
	rule46 = ctrl.Rule(flame['medium'] & distance['low'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule47 = ctrl.Rule(flame['medium'] & distance['low'] & pir['high'] & temp['medium'] , cost['high'])
	rule48 = ctrl.Rule(flame['medium'] & distance['low'] & pir['high'] & temp['low'] , cost['medium'])
	rule49 = ctrl.Rule(flame['medium'] & distance['low'] & pir['medium'] & temp['high'] , cost['veryhigh'])
	rule50 = ctrl.Rule(flame['medium'] & distance['low'] & pir['medium'] & temp['medium'] , cost['high'])
	rule51 = ctrl.Rule(flame['medium'] & distance['low'] & pir['medium'] & temp['low'] , cost['low'])
	rule52 = ctrl.Rule(flame['medium'] & distance['low'] & pir['low'] & temp['high'] , cost['veryhigh'])
	rule53 = ctrl.Rule(flame['medium'] & distance['low'] & pir['low'] & temp['medium'] , cost['high'])
	rule54 = ctrl.Rule(flame['medium'] & distance['low'] & pir['low'] & temp['low'] , cost['low'])
	rule55 = ctrl.Rule(flame['low'] & distance['high'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule56 = ctrl.Rule(flame['low'] & distance['high'] & pir['high'] & temp['medium'] , cost['high'])
	rule57 = ctrl.Rule(flame['low'] & distance['high'] & pir['high'] & temp['low'] , cost['medium'])
	rule58 = ctrl.Rule(flame['low'] & distance['high'] & pir['medium'] & temp['high'] , cost['veryhigh'])
	rule59 = ctrl.Rule(flame['low'] & distance['high'] & pir['medium'] & temp['medium'] , cost['high'])
	rule60 = ctrl.Rule(flame['low'] & distance['high'] & pir['medium'] & temp['low'] , cost['low'])
	rule61 = ctrl.Rule(flame['low'] & distance['high'] & pir['low'] & temp['high'] , cost['high'])
	rule62 = ctrl.Rule(flame['low'] & distance['high'] & pir['low'] & temp['medium'] , cost['medium'])
	rule63 = ctrl.Rule(flame['low'] & distance['high'] & pir['low'] & temp['low'] , cost['verylow'])
	rule64 = ctrl.Rule(flame['low'] & distance['medium'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule65 = ctrl.Rule(flame['low'] & distance['medium'] & pir['high'] & temp['medium'] , cost['high'])
	rule66 = ctrl.Rule(flame['low'] & distance['medium'] & pir['high'] & temp['low'] , cost['low'])
	rule67 = ctrl.Rule(flame['low'] & distance['medium'] & pir['medium'] & temp['high'] , cost['high'])
	rule68 = ctrl.Rule(flame['low'] & distance['medium'] & pir['medium'] & temp['medium'] , cost['medium'])
	rule69 = ctrl.Rule(flame['low'] & distance['medium'] & pir['medium'] & temp['low'] , cost['low'])
	rule70 = ctrl.Rule(flame['low'] & distance['medium'] & pir['low'] & temp['high'] , cost['high'])
	rule71 = ctrl.Rule(flame['low'] & distance['medium'] & pir['low'] & temp['medium'] , cost['medium'])
	rule72 = ctrl.Rule(flame['low'] & distance['medium'] & pir['low'] & temp['low'] , cost['verylow'])
	rule73 = ctrl.Rule(flame['low'] & distance['low'] & pir['high'] & temp['high'] , cost['veryhigh'])
	rule74 = ctrl.Rule(flame['low'] & distance['low'] & pir['high'] & temp['medium'] , cost['veryhigh'])
	rule75 = ctrl.Rule(flame['low'] & distance['low'] & pir['high'] & temp['low'] , cost['medium'])
	rule76 = ctrl.Rule(flame['low'] & distance['low'] & pir['medium'] & temp['high'] , cost['veryhigh'])
	rule77 = ctrl.Rule(flame['low'] & distance['low'] & pir['medium'] & temp['medium'] , cost['high'])
	rule78 = ctrl.Rule(flame['low'] & distance['low'] & pir['medium'] & temp['low'] , cost['medium'])
	rule79 = ctrl.Rule(flame['low'] & distance['low'] & pir['low'] & temp['high'] , cost['veryhigh'])
	rule80 = ctrl.Rule(flame['low'] & distance['low'] & pir['low'] & temp['medium'] , cost['high'])
	rule81 = ctrl.Rule(flame['low'] & distance['low'] & pir['low'] & temp['low'] , cost['low'])

	
	cost_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5,rule6,rule7,rule8,rule9,rule10,rule11,rule12,rule13,rule14,rule15,rule16,rule17,rule18,rule19,rule20,rule21,rule22,rule23,rule24,rule25,rule26,rule27,rule28,rule29,rule30,rule31,rule32,rule33,rule34,rule35,rule36,rule37,rule38,rule39,rule40,rule41,rule42,rule43,rule44,rule45,rule46,rule47,rule48,rule49,rule50,rule51,rule52,rule53,rule54,rule55,rule56,rule57,rule58,rule59,rule60,rule61,rule62,rule63,rule64,rule65,rule66,rule67,rule68,rule69,rule70,rule71,rule72,rule73,rule74,rule75,rule76,rule77,rule78,rule79,rule80,rule81])
	cost = ctrl.ControlSystemSimulation(cost_ctrl)
	cost.input['flame'] = val1
	cost.input['distance'] = val3
	cost.input['pir'] = val2
	cost.input['temp'] = val4
	cost.compute()
	return(round(cost.output['cost']))

